Fix form builder deselecting gender radio buttons
hitobito/hitobito_sac_cas pull request #1102
Opened 2024-10-10 09:29 UTC by hunchr

Fixes #1100

2024-10-11 08:47 UTC, amaierhofer requested changes
Bitte noch auf standard presence validierung umbauen, sollte klappen weil der browser ja `_nil` schickt für das diverse Geschlecht

2024-10-11 08:47 UTC, amaierhofer commented on app/models/wizards/signup/sektion_operation.rb
> +      person_attrs[:gender] = nil if person_attrs[:gender] == I18nEnums::NIL_KEY
Das verhalten sollten man noch mit einer spec abdecken

2024-10-11 08:47 UTC, amaierhofer commented on app/models/wizards/steps/signup/sektion/person_fields.rb
> +    validate :require_gender
analog family member

2024-10-11 08:47 UTC, amaierhofer commented on app/models/wizards/steps/signup/sektion/family_fields/member.rb
> +    validate :require_gender
Kann das nicht über eine normale presence validierung gemacht werden? Sollte doch klappen wenn der Browser den `I18nEnums::NIL_KEY` schickt oder?

2024-10-11 08:47 UTC, amaierhofer commented on app/models/wizards/steps/signup/sektion/family_fields/member.rb
> +      %i[email_required phone_number_required gender]
das `gender` könnte hier raus, wenn das über die normale `presence` validerung gemacht wird

2024-10-11 08:47 UTC, amaierhofer commented on app/models/wizards/steps/signup/sektion/family_fields/member.rb
> +    def require_gender
obsolete wenn normale presence validerung klappt

2024-10-11 08:47 UTC, amaierhofer commented on spec/models/wizards/signup/sektion_wizard_spec.rb
> +        gender: "",
Hier `_nil` analog FormBuilder setzen

2024-10-11 08:47 UTC, amaierhofer commented on spec/models/wizards/steps/signup/sektion/person_fields_spec.rb
> +      gender: "",
Hier `_nil` analog FormBuilder setzen

2024-10-11 09:35 UTC, hunchr commented on app/models/wizards/steps/signup/sektion/family_fields/member.rb
> +    validate :require_gender
stimmt, als ich das angepasst habe, habe ich vergessen die custom validation wieder zu entfernen

2024-10-11 10:00 UTC, hunchr commented
getestet im UI

2024-10-15 12:38 UTC, amaierhofer approved these changes
LGTM :rocket:

2024-10-15 12:47 UTC, merged