Task/sac 95 family self registration
hitobito/hitobito_sac_cas pull request #113
Opened 2023-10-16 11:06 UTC by amaierhofer

refs #95

2023-10-18 13:27 UTC, carlobeltrame requested changes

2023-10-18 13:27 UTC, carlobeltrame commented on app/controllers/sac_cas/groups/self_registration_controller.rb
> +class SacCas::Groups::SelfRegistrationController < ApplicationController
Lieber nicht den ganzen Controller ersetzen, sondern die Changes in den Core verschieben und dort Defaults wählen sodass die SelfRegistration im Core nicht gross abgeändert wird. Dann im SAC Wagon die effektiven SAC-spezifischen Steps einfügen.

Durch das Ersetzen hast du aus Versehen die `add_newsletter_label` Logik kaputt gemacht.

2023-10-18 13:27 UTC, carlobeltrame commented on components/application_component.rb
> +class ApplicationComponent < ViewComponent::Base
Hier hast du irgendwie eine Kopie des ganzen `components` Ordners ausserhalb von `app` gemacht..? Sollten wir wieder entfernen

2023-10-19 07:09 UTC, amaierhofer commented on app/assets/javascripts/wagon.js.coffee
> +- #  Copyright (c) 2023, Schweizer Alpen-Club. This file is part of
Ich würde die stimulus geschichte lieber erst mal hier im wagon behalten. Bei mir läufts durch hab mehrmals 
`RAILS_ENV=test rails webpacker:compile` gemacht.

2023-10-19 07:11 UTC, amaierhofer commented on app/components/application_component.rb
> +class ApplicationComponent < ViewComponent::Base
Die Methoden der Klassen machen nur dann Sinn, wenn im core auch schon stimulus laden

2023-10-19 07:27 UTC, amaierhofer commented on components/application_component.rb
> +class ApplicationComponent < ViewComponent::Base
Idee wäre, dass alles mal nur im wagon zu lassen bis wir das feature validiert haben

2023-11-27 20:28 UTC, carlobeltrame commented on components/application_component.rb
> +class ApplicationComponent < ViewComponent::Base
Es gilt weiterhin: Es gibt jetzt Kopien der Dateien unter rails_root/components/*.rb sowie rails_root/**app**/components/*.rb. Ich nehme an das war ein Copy Paste Fehler. Bitte den components Ordner der ausserhalb von app/ liegt löschen, diese Dateien ausserhalb vom app/ haben keinen Effekt.

2023-11-27 20:33 UTC, carlobeltrame commented on app/views/sac_cas/groups/self_registration/new.html.haml
> +- #  Copyright (c) 2023, Schweizer Alpen-Club. This file is part of
Ich glaube diese Datei brauchts hier nicht mehr oder?

2023-11-30 12:06 UTC, merged