Task/117 improve people import
hitobito/hitobito_sac_cas pull request #120
Opened 2023-10-20 10:01 UTC by amaierhofer

2023-10-23 15:01 UTC, daniel-illi commented on lib/hitobito_sac_cas/import/section/member.rb
> +        @emails = emails
`@existing_emails` wäre sprechender

2023-10-23 15:05 UTC, daniel-illi commented on lib/hitobito_sac_cas/import/section/members_importer.rb
> +        output.puts "CAN NOT IMPORT ROW WITH NAVISION ID: #{row[:navision_id]}\n#{e.message}"
Sollten diese noch zu `@errors` hinzugefügt werden?

2023-10-25 11:42 UTC, mtnstar requested changes
thx so far for this nice clean-up :partying_face: 

I'm finishing it now

2023-10-25 11:42 UTC, mtnstar commented on lib/hitobito_sac_cas/wagon.rb
> +      #{config.root}/lib/hitobito_sac_cas
ja, ich nehme das wieder raus und wir laden die abhängigkeiten mit require_relative.
wir brauchen die importer klassen ja zu normalen rails laufzeit nie

2023-10-26 13:55 UTC, amaierhofer commented
Die neue validierungen auf der Rolle hat einiges an specs kaputt gemacht. Ich habe das nachgezogen. Die importer sind weiterhin im autoload path drinnen. Damit ersparen wir uns das unschöne `require_relative`

2023-10-26 14:09 UTC, merged