Only show self employed checkbox and field for leaders
hitobito/hitobito_sac_cas pull request #1246
Opened 2024-11-17 01:43 UTC by rnestler

2024-11-21 18:38 UTC, rnestler commented on app/views/event/participations/_roles_sac_cas.html.haml
> +  = self_employed_label(role)
So this does only work if all the roles have the same kind. If there are multiple roles available which may or may not have kind `:leader` then we'd need to switch using stimulus.

2024-11-27 12:15 UTC, codez requested changes
Grundsätzlich ok. Allerdings fehlt bei den einzelnen Partials noch die Überprüfung, ob es sich beim Event auch um einen Kurs handelt. Bei regulären Anlässen soll diese Information/Checkbox nicht angezeigt werden.

2024-11-27 20:22 UTC, rnestler commented
> Grundsätzlich ok. Allerdings fehlt bei den einzelnen Partials noch die Überprüfung, ob es sich beim Event auch um einen Kurs handelt. Bei regulären Anlässen soll diese Information/Checkbox nicht angezeigt werden.

Hab ich im Ticket übersehen :see_no_evil: hinzugefügt inklusive request spec.

2024-11-29 13:21 UTC, rnestler commented
@codez Fixed.

2024-12-03 07:29 UTC, TheWalkingLeek approved these changes
Habs auch noch durchgeklickt und schaut gut aus :)

2024-12-03 07:54 UTC, merged