Feature/sac 98 families
hitobito/hitobito_sac_cas pull request #134
Opened 2023-11-07 09:12 UTC by daniel-illi

Fixes #98

2023-11-09 11:03 UTC, mtnstar commented
ich habe beim manuellen Testen:

1. Ein bestehende Familie genommen
2. Dort eine Erwachsene Person hinzugefügt
3. Dann dieser Person eine Mitglied Rolle in der selben Sektion wie die Familie gegeben
4. :boom: 

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/c670fd90-39a5-48d9-b7fc-1da1315646cc)

2023-11-13 15:08 UTC, mtnstar commented
wenn ich den mitglieder import laufen lasse:

```
usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:105:in `rescue in import_person'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:90:in `import_person'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:84:in `import_row'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:51:in `block (2 levels) in import!'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:59:in `block (2 levels) in each_row'
/usr/src/app/hitobito/lib/import/xlsx_reader.rb:17:in `read'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:58:in `block in each_row'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:118:in `without_query_logging'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:57:in `each_row'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:51:in `block in import!'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:71:in `with_file'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:50:in `import!'
/usr/src/app/hitobito_sac_cas/lib/tasks/import/import.rake:26:in `block (2 levels) in <main>'
/usr/src/app/hitobito/bin/rails:4:in `<main>'

Caused by:
ActiveRecord::RecordInvalid: Gültigkeitsprüfung ist fehlgeschlagen: Rollen ist nicht gültig
/usr/src/app/hitobito_sac_cas/app/models/sac_cas/role.rb:27:in `set_preferred_primary!'
/usr/src/app/hitobito_sac_cas/app/models/sac_cas/role.rb:23:in `reset_primary_group'
/usr/src/app/hitobito/app/models/role.rb:159:in `destroy'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:91:in `import_person'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:84:in `import_row'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:51:in `block (2 levels) in import!'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:59:in `block (2 levels) in each_row'
/usr/src/app/hitobito/lib/import/xlsx_reader.rb:17:in `read'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:58:in `block in each_row'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:118:in `without_query_logging'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:57:in `each_row'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:51:in `block in import!'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:71:in `with_file'
/usr/src/app/hitobito_sac_cas/lib/hitobito_sac_cas/import/sektion/mitglieder_importer.rb:50:in `import!'
/usr/src/app/hitobito_sac_cas/lib/tasks/import/import.rake:26:in `block (2 levels) in <main>'
/usr/src/app/hitobito/bin/rails:4:in `<main>'
Tasks: TOP => import:sektions_mitglieder
(See full trace by running task with --trace)
```

das hat vermutlich was mit dem merge der hauptsektion (stammsektion) zu tun?!

2023-11-13 15:13 UTC, mtnstar commented
wenn ich versuche einer Person eine Mitglied rolle zu vergeben:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/ba38a6d8-b1b2-4998-981f-b5587a2f6620)

1. Navigation zu Gruppe Blüemlisalp > Mitglieder
2. Person hinzufügen
3. Person wählen sowie Mitglied Rolle auswählen
4. :boom:

2023-11-13 15:26 UTC, mtnstar requested changes
cool, das sieht schon sehr gut aus und geht in die richtige Richtung :rocket: 

- bitte mal noch die specs fixen sowie sicherstellen das der mitglieder import funktioniert.
- household_key muss von mir aus nicht 1:1 aus import file übernommen werden, lieber die eigene Logik verwenden
- Bitte auch testen ob eine Familie manuell erstellt werden kann, ohne den Importer

schaue dann gerne nochmals über diesen PR wenn alles gefixt ist.
wir können gerne noch syncen

2023-11-13 15:26 UTC, mtnstar commented on app/models/sac_cas/role/mitglied_family_validations.rb
> +    adult_housemates_count = person.
könnte man dies nicht in eine eigene oder gar mehrere methode auslagern?
einrücken?

2023-11-15 08:37 UTC, daniel-illi commented on app/domain/sac_cas/beitragskategorie/calculator.rb
> +    AGE_MINOR_FAMILY_MEMBER = AGE_YOUTH.begin..16
right :+1:

2023-11-15 08:43 UTC, daniel-illi commented on app/domain/sac_cas/beitragskategorie/calculator.rb
> +    AGE_YOUTH = 6...AGE_ADULT.begin
nö das stimmt doch schon so wie es ist, mit den `...` ist der end value ja excluded

2023-11-15 08:45 UTC, daniel-illi commented on app/domain/sac_cas/person/household.rb
> +    person.update(household_key: nil)
good point :+1:

2023-11-15 12:30 UTC, mtnstar commented on app/domain/sac_cas/beitragskategorie/calculator.rb
> +    AGE_YOUTH = 6...AGE_ADULT.begin
ah ok ... das war nicht nicht klar.

2023-11-15 16:30 UTC, daniel-illi commented on app/abilities/sac_cas/person_ability.rb
> +  end
outdated. dieser change gehört nicht zu diesem feature sondern zu einem PR auf welchem dieser PR vorher basiert hat.

2023-11-20 12:49 UTC, merged