Step through course state
hitobito/hitobito_sac_cas pull request #488
Opened 2024-04-19 06:27 UTC by TheWalkingLeek

Refs: #362

2024-04-23 11:11 UTC, codez requested changes
Das Feld "Status" im Bearbeitenformular soll noch entfernt werden.

2024-04-23 11:11 UTC, codez commented on config/locales/wagon.de.yml
> +      success: Status wurde auf %{state} gesetzt.
Die top-level Keys unbedingt immer alphabetisch einordnen. Jetzt gibt es keinen Merge Conflict mit dem neuen `events.form_tabs.communication`, dafür einen 500er wenn man auf die entsprechende Seite geht...

2024-05-03 11:11 UTC, codez requested changes
Ich sehe keine Änderung, welche das Status Feld im Formular entfernt (siehe Issue). Fehlt das noch oder kam das woanders mit?

2024-05-03 11:11 UTC, codez commented on app/controllers/events/courses/state_stepping_controller.rb
> +  def step_possible?
Die Methode könnte noch vor dem Update aufgerufen werden, um nicht vorgesehene Wechsel zu verhindern (falls jemand den Request mit ungültigen Params macht). Momentan wird sie gar nicht gebraucht.

2024-05-07 11:00 UTC, codez commented on app/models/sac_cas/event/course.rb
> +      :state
Achtung, das blendet den Status auch auf der Show Seite aus, was nicht gewünscht ist... Nur das Feld im Formular soll weg. Siehe auch Beschreibung im Ticket.

2024-05-23 04:39 UTC, mtnstar requested changes
nice :partying_face: 
ich habe die review feedbacks gleich selber umgesetzt.
wenn der build dann durchläuft werde ich das feature gleich selber mergen

2024-05-23 04:39 UTC, mtnstar commented on app/controllers/events/courses/state_stepping_controller.rb
> +class Events::Courses::StateSteppingController < ApplicationController
```suggestion
class Events::Courses::StateController < ApplicationController
```

2024-05-23 14:12 UTC, merged