Support adding external_trainings for multiple people (#524)
hitobito/hitobito_sac_cas pull request #542
Opened 2024-05-14 13:31 UTC by amaierhofer

2024-05-21 05:37 UTC, mtnstar commented
![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/3a278923-3d64-4fa7-89ba-b27f0821ee46)

sollte die Person selber auch auswählbar sein? Die Externe Ausbildung wird ja für diese Person erfasst, nicht?

2024-05-21 06:05 UTC, mtnstar commented
ux-technisch fände ich es noch gut wenn das Feld für die zusätzlichen Personen visuell etwas abgekapselt vom Formualar daher kommt:

![image](https://github.com/hitobito/hitobito_sac_cas/assets/655627/f608cc9c-d3aa-4ff1-93da-cb8860227d5c)

2024-05-21 07:19 UTC, Largo commented
Grundsaetzlich funktionierts. Hier noch was mir aufgefallen ist. Teilweise vermutlich auch nicht direkt dieser Code:

In der Uebersicht ueberlappt der Text wenn das Fenster 3/4 des Bildschirms weit ist.
![image](https://github.com/hitobito/hitobito_sac_cas/assets/170974/6a4ba1a7-387b-46bc-9edd-d2ac415b2e74)

Die neu angelegte externe Qualifikation taucht nirgends mehr auf? wie finde ich die anderen Personen wieder, welche wir mit dem Typeahead hinzugefuegt haben?

Mann kann den Kurznamen auslassen beim erstellen, aber an einem anderen Ort (Edit Formular) ist der ein Pflichtfeld.

Beim Auswaehlen von Kursart (keine) kommt bei mir beim speichern folgender Fehler:

**ActiveRecord::NotNullViolation** at /de/groups/8/people/600496/external_training
Mysql2::Error: Field 'event_kind_id' doesn't have a default value

Ansonsten scheints gut zu sein. Der Typeahead ist auch schoen debounced. Prima.

2024-05-21 09:31 UTC, daniel-illi commented on app/views/external_trainings/_form.html.haml
> +  = f.labeled(:other_people_ids, '', data: { controller: :tom_select }) do
@amaierhofer auf Zeile 15 wird der 'tom-select' controller ebenfalls angehängt. Eines ist wohl zu viel?

2024-05-22 04:56 UTC, mtnstar requested changes
sieht doch schon super aus :partying_face: :rocket: 

- Ich fände es gut wenn wie bereits erwähnt das Input Field für die weiteren Personen abgekapselt wäre vom Rest des Formulars
- Die Person selber sollte man nicht hinzufügen können
- Die Success Flash Message sollte die Personen auflisten für die die Ausbildung erfolgreich erfasst wurde. Am besten gleich mit klickbaren person show links

2024-05-22 04:56 UTC, mtnstar commented on app/controllers/external_trainings_controller.rb
> +    Person.accessible_by(PersonWritables.new(current_user))
abzüglich der param[:person_id] ?

2024-05-22 04:56 UTC, mtnstar commented on app/controllers/person/query_external_training_controller.rb
> +    Person.accessible_by(PersonWritables.new(current_user)).distinct.joins(roles: :group)
auch hier irgendwie ohne die aktuell ausgewählte Person

2024-05-22 04:56 UTC, mtnstar commented on spec/controllers/external_trainings_controller_spec.rb
> +        it 'ignores person for which current user has no write permission' do
:+1:

2024-05-22 13:23 UTC, amaierhofer commented on app/controllers/external_trainings_controller.rb
> +    Person.accessible_by(PersonWritables.new(current_user))
- hab das Feld via `field_set_tag` abgekapselt und einen help_text ergänzt, formatierung wie im screenshot scheint momentan vom `StandardFormBuilder` nicht unterstützt zu sein
- Person selber kann man zwar hinzufügen aber Trainnig wird nur 1x erstellt
- Personen werden im flash aufgelistet (ohne link)

2024-05-22 14:58 UTC, merged