Feature/sac 502 membership invoice
hitobito/hitobito_sac_cas pull request #546
Opened 2024-05-15 13:15 UTC by codez

2024-05-16 15:15 UTC, mtnstar requested changes
sieht schon ziemlich gut aus :partying_face: :rocket: 

beim Naming fände ich es gut wenn wir wie ich es vorgeschlagen habe darauf verzichten würden Sac spezifische Begriffe ins Englische zu übersetzen. Wir verhindern so auch das die gleichen Begriffe mehrfach anders übersetzt werden. 

gewissen Code wie z.B. Konstanten an zentrale Orte wie z.B. app/domain/sac_cas.rb auslagern?

2024-05-16 16:04 UTC, codez commented
Merci für das Review, ich werden die Rückmeldungen nächste Woche einbauen.

> beim Naming fände ich es gut wenn wir wie ich es vorgeschlagen habe darauf verzichten würden Sac spezifische Begriffe ins Englische zu übersetzen. Wir verhindern so auch das die gleichen Begriffe mehrfach anders übersetzt werden.

Kannst du in dem Fall bitte auch gleich alle Attribute der `SacMembershipConfig` / `SectionMembershipConfig` auch anpassen? Insbesondere wären da noch die Beitragskategorien-Suffixe, welche wir in dem Fall auch gleich auf Deutsch benennen können. Zudem hat's dort auch noch einzelne `section` drin.

2024-05-16 16:05 UTC, codez commented on app/domain/invoices/memberships/person.rb
> +        @main_membership_role ||= active_roles_of_type(Group::SektionsMitglieder::Mitglied).first
Da die Rollen alle preloaded sind, ist das die effektivste Variante, oder?

2024-05-16 16:41 UTC, mtnstar commented
ich schaue mal das ganze Repo durch und versuche das noch zu Bereinigen.

ggf. werde ich auch noch einen Glossar im doc Folder erstellen.

ggf. könntest du noch ein paar Doku Zeilen in https://github.com/hitobito/hitobito_sac_cas/blob/master/doc/README.md hinterlegen.

2024-05-16 16:58 UTC, mtnstar commented on app/domain/invoices/memberships/person.rb
> +        @main_membership_role ||= active_roles_of_type(Group::SektionsMitglieder::Mitglied).first
> Da die Rollen alle preloaded sind, ist das die effektivste Variante, oder?

das stimmt.

Die aktive Stammsektions-Rolle einer Person zu fetchen ist aber sicher was das immer wieder mal vorkommt. 
vielleicht macht es Sinn hier einen default way/getter zu definieren

2024-05-17 08:38 UTC, carlobeltrame commented
> > beim Naming fände ich es gut wenn wir wie ich es vorgeschlagen habe darauf verzichten würden Sac spezifische Begriffe ins Englische zu übersetzen. Wir verhindern so auch das die gleichen Begriffe mehrfach anders übersetzt werden.
> 
> Kannst du in dem Fall bitte auch gleich alle Attribute der `SacMembershipConfig` / `SectionMembershipConfig` auch anpassen? Insbesondere wären da noch die Beitragskategorien-Suffixe, welche wir in dem Fall auch gleich auf Deutsch benennen können. Zudem hat's dort auch noch einzelne `section` drin.
> 
> > ich schaue mal das ganze Repo durch und versuche das noch zu Bereinigen.

@codez @mtnstar Ich finde das mit den deutschen Begriffen mehr und mehr eine schlechte Idee. Die ursprüngliche Prämisse unter der ich diese Abweichung von hitobito-Standard-Practice mal akzeptiert hatte war, dass es nur für uns deutschsprachige Devs einen Unterschied macht. Allerdings ist inzwischen aufgefallen, dass diese Klassennamen und internen Begriffe auch in der API (z.B. als Query Parameter und in den Responses) und in OIDC (z.B. Rollenbezeichnungen) vorkommen und somit auch die Aussenwelt betreffen. Würden wir jetzt SAC-spezifische Attribute auch noch auf deutsch benennen, dann wäre in unserem Code wie auch in der API plötzlich einige nebeneinanderstehende Begriffe auf englisch und einige auf deutsch, was aus meiner Sicht nochmals eine Verschlechterung wäre (bisher sind wenigstens konsistent alle Gruppentypen und Rollentypen deutsch, alles andere englisch).

Der SAC ist eine Organisation bei der die Sprache (und der nicht zu hohe Fokus auf deutsch) so wichtig ist, dass sie nicht einmal sac.ch als ihre Domain nutzen dürfen, sondern sac-cas.ch verwenden müssen. Dies spricht für mich weiter dafür, dass wir, wenn wir jetzt noch etwas ändern, besser alles auf englisch übersetzen sollten. Jedenfalls sollten wir nicht noch mehr deutsch einführen als wir es bis jetzt haben.

2024-05-18 08:50 UTC, codez commented
@carlobeltrame @mtnstar Eine durchaus valable Argumentation. Ich bin grundsätzlich auch pro Englisch, wollte mich hier aber raushalten. 

Gruppen/Rollen deutsch und alles andere Englisch tönt für mich gut. Allerdings würde ich momentan nicht zu viel Aufwand in eine Umstellung stecken. Aber besprecht das Thema doch am nächsten Daily, um eine gemeinsame Entscheidung zu finden und künftige Namen konsistenter zu wählen. 

Unschön wird es insbesondere auch, wenn Attribute gemischtsprachig sind (sektion_entry_fee_einzel). Die Beitragskategorie könnte imho gut auch Englisch sein, allerdings würde eine Umstellung wohl eine Datenmigration bedingen. Bei der Section sehe ich auch nicht so grosse Probleme, da der Gruppentyp und der Layoutbereich doch fachlich weit genug auseinander sind, als dass ich da Missverständnisse erwarte.

2024-05-24 14:36 UTC, codez commented on app/domain/invoices/memberships/person.rb
> +      def active_roles
Dort geht's ja nur um `Group::SektionsMitglieder::Mitglied`, hier noch um diverse andere

2024-05-24 16:05 UTC, merged