Feature/sac 530 people analoger mitgliederausweis
hitobito/hitobito_sac_cas pull request #568
Opened 2024-05-27 10:19 UTC by Largo

WIP #530

2024-05-29 13:51 UTC, amaierhofer requested changes
Folgendes muss noch mit dem Kunden geklärt werden
- [ ] Wie umgehen mit langen und überlangen Namen?

Folgendes stimmt noch nicht mit der Spezifikation überein
- [ ] Land mehrsprachig ausgeben ev. (`::Person::Address.new(person).for_membership_pass, `ISO3166::Country.new("CH").translated_names`)

Folgende refactorings fände ich noch sinnvoll
- [ ] weniger magic numbers, beim pdf generieren, dafür sprechende konstanten
- [ ] notfallkontakt in die locales
- [ ] Link zum Ausweis nur anzeigen falls eine Mitgliedschaft besteht?
- [ ] Alignment vom Button überdenken (betrifft noch weitere buttons auf der Seite)

2024-05-29 13:51 UTC, amaierhofer commented on app/domain/export/pdf/passes/membership/person.rb
>      def render
Hier müssen wir uns noch was überlegen bzw mit dem SAC klären. 

Aktuell führt ein längere Name zu overflows (siehe screenshot)  
![image](https://github.com/hitobito/hitobito_sac_cas/assets/180780/6f8da611-42c1-4f30-af9a-1c10b4885a0d)
und wenns noch länger wird dann knallts  `Table's width was set too small to contain its contents (min width 263.638, requested 260)`

2024-05-29 13:51 UTC, amaierhofer commented on app/domain/export/pdf/passes/membership/footer.rb
> +        ["Notfallnummer / N° d'urgence / No. di emergenza",
Fände ich persönlich besser in den locales, zb  unter `global.emergency_contact_number` und dann mit `I18n.with_locale(..) { I18n.t('global.emergency_contact_number') }` auslesen

2024-05-29 13:51 UTC, amaierhofer commented on app/domain/export/pdf/passes/membership/footer.rb
> +      pdf.image(reciprocity_image_path, position: :left, at: [496.714, 190.213],
Die `at: ` params würden mir als Konstanten mit sprechenden Namen besser gefallen.

2024-05-29 13:51 UTC, amaierhofer commented on app/domain/export/pdf/passes/membership/footer.rb
> +      text_box 'REGA 1414                    SOS Europe 112',
das denke ich kann im code bleiben (Konstante?) und sollte nicht in die locales

2024-05-29 13:51 UTC, amaierhofer commented on app/domain/export/pdf/passes/membership/footer.rb
> +                 at: [489.973,
fände ich auch als sprechende konstante besser

2024-05-29 13:51 UTC, amaierhofer commented on app/domain/export/pdf/passes/membership/footer.rb
> +      fill_color('EFEFEF') do
Farben ebenfalls als Konstante besser

2024-05-29 13:51 UTC, amaierhofer commented on app/domain/export/pdf/passes/membership/footer.rb
> +      bottom = 37
würde ich eine zeile raufnehmen

2024-05-29 13:51 UTC, amaierhofer commented on app/domain/export/pdf/passes/membership/footer.rb
> +      membership_card_height = 162
wäre auch kandidate für eine konstante

2024-05-30 09:45 UTC, Largo commented
Besten Dank fürs review. Zu  "Alignment vom Button überdenken" bitte noch Klarifizierung, evtl zusammen mit lead dev.

2024-05-31 14:15 UTC, amaierhofer commented
Dropdown sieht gut aus, ich bekomme allerdings immer noch ein 404 mit meinem User mit einer abgelaufenen mitgliedschaft, siehe https://github.com/hitobito/hitobito_sac_cas/blob/2d7df8ce5f9e8589e07d28a0915988cb9fc8e689/app/domain/sac_cas/people/membership/verifier.rb#L12
Frag doch nochmal bei @mtnstar was da jetzt genau gilt.

2024-06-04 12:46 UTC, Largo commented
okay, danke fuers review. jetzt gehts und werde es mergen.

2024-06-04 13:32 UTC, merged