EVENTS: Qualifikationen nicht in der Zukunft erfassbar
hitobito/hitobito_sac_cas pull request #675
Opened 2024-06-24 15:19 UTC by hunchr

Fixes #539

![image](https://github.com/hitobito/hitobito_sac_cas/assets/76159444/e94e2167-1b16-4f71-8e0e-8be72e626182)

2024-07-02 08:49 UTC, amaierhofer requested changes

2024-07-02 08:49 UTC, amaierhofer commented on app/controllers/sac_cas/qualifications_controller.rb
> +      entry.save context: :qualifications_controller_create
ich finde es besser wenn wir statt `create` `save_entry` vom `CrudController` überschreiben

2024-07-02 08:49 UTC, amaierhofer commented on app/models/sac_cas/qualification.rb
> +    errors.add(:start_at, :must_be_in_past) if start_at.present? && start_at > Time.zone.today
statt zwei conditionals würde auch `start_at&.future?` ausreichen

2024-07-02 08:49 UTC, amaierhofer commented on spec/models/qualification_spec.rb
> +  it 'is valid when start_at is in the future' do
Fände noch einen test gut, der mit dem spezifischem validation context testet und validiert, dass die quali dort nicht valid ist

2024-07-02 10:06 UTC, hunchr commented on app/controllers/sac_cas/qualifications_controller.rb
> +      entry.save context: :qualifications_controller_create
stimmt, aber dann wird nicht nur bei `create` validiert sondern immer für den controller. ist das egal?

2024-07-03 06:31 UTC, amaierhofer approved these changes
LGTM :+1:

2024-07-03 07:22 UTC, merged