Validate external trainings to not have finish_at in future
hitobito/hitobito_sac_cas pull request #676
Opened 2024-06-25 06:58 UTC by TheWalkingLeek

Refs: hitobito/hitobito_sac_cas#538

2024-06-25 08:41 UTC, rnestler approved these changes

2024-06-25 08:41 UTC, rnestler commented on app/models/external_training.rb
>            start_date: start_date, end_date: end_date).distinct
This can be simplified:
```suggestion
    where(start_at: ..end_date, finish_at: start_date..).distinct
```

2024-06-25 08:41 UTC, rnestler commented on spec/models/external_training_spec.rb
> +  let(:today) { Date.current }
Working with `Date.current` may lead to flaky specs. Not in this case I think, but generally. Consider using https://github.com/travisjeffery/timecop to freeze the current time, so `Date.current` returns the same for the whole execution of the spec.

2024-07-02 07:44 UTC, amaierhofer requested changes
Ich finde die Vorschläge von @rnestler gut, bitte noch einpflegen.

2024-07-04 06:52 UTC, merged