Feature/627 Wizard austritt zusatzsektion
hitobito/hitobito_sac_cas pull request #679
Opened 2024-06-25 17:14 UTC by rnestler

2024-06-26 08:28 UTC, amaierhofer requested changes

2024-06-26 08:38 UTC, rnestler commented on spec/components/previews/wizards_preview.rb
> +  def leave_zusatzsektion_wizard(current_step: 0, step: 0, next: nil,
Nicht wirklich, aber es hat gereicht um alle steps mal zu rendern.

2024-06-26 08:43 UTC, rnestler commented on app/models/wizards/memberships/leave_zusatzsektion.rb
> +    def step_after(step_class_or_name)
Ja gefällt mir auch nicht so gut... Ein Problem ist, dass wir für alle "end-steps" `nil` zurückgeben müssen, was boiler platy ist..

2024-06-28 13:10 UTC, rnestler commented on app/models/wizards/memberships/leave_zusatzsektion.rb
> +      leave_operation.valid?.tap do
Lass uns mal die zwei Wizards unabhängig implementieren und dann beim dritten eine Basisklasse erstellen.

2024-06-28 13:13 UTC, rnestler commented on app/models/wizards/memberships/leave_zusatzsektion.rb
> +      step(:choose_date)&.terminate_on == 'now' ? Date.current : Date.current.end_of_year
Ich bin mir nicht sicher ob ich das so richtig mag. Finde so hidden magic manchmal eher unintuitiv. Mit `step(:...)` sieht man direkt dass auf einen step zugegriffen wird.

2024-07-08 13:07 UTC, rnestler commented on app/models/wizards/memberships/leave_zusatzsektion.rb
> +    def step_after(step_class_or_name)
Hab die Logik umgekehrt, jetzt ist es einiges einfacher.

2024-07-09 12:28 UTC, daniel-illi reviewed
LGTM :+1: 

Habe erst jetzt realisiert, dass das `Memberships::LeaveZusatzsektion` den Austrittsgrund noch gar nicht berücksichtigt.
Eine fixture für `TerminationReason` gibts aber, diese kann in den Tests verwendet werden. Ich habe noch einen commit gepusht mit einem seed file für die dev Umgebung. 
Kannst du die Tests noch anpassen, dass die fixture verwendet wird statt die dummy values?
Ich erstelle ein Folgeticket damit der Austrittsgrund noch ans `LeaveZusatzsektion` durchgereicht werden kann und von diesem persistiert wird.

2024-07-09 12:28 UTC, daniel-illi commented on app/views/wizards/steps/leave_zusatzsektion/_summary.html.haml
> +    = form.select :termination_reason, ['einfach so', 'weiss nicht'], {prompt: true}
```ruby
form.labeled_collection_select :termination_reason_id, c.model.termination_reasons, :id, :text, {prompt: true}
```

und auf dem `Wizards::Steps::LeaveZusatzsektion::Summary`:
```ruby
def termination_reasons
  TerminationReason.all
end
```

2024-07-09 12:28 UTC, daniel-illi commented on spec/features/memberships/leave_zusatzsektion_spec.rb
> +      select "einfach so"
Wert aus fixtures verwenden (spec/fixtures/termination_reasons.yml)

2024-07-09 12:28 UTC, daniel-illi commented on spec/features/memberships/leave_zusatzsektion_spec.rb
> +      select "einfach so"
Wert aus fixtures verwenden (spec/fixtures/termination_reasons.yml)

2024-07-09 12:28 UTC, daniel-illi commented on spec/features/memberships/leave_zusatzsektion_spec.rb
> +      select "einfach so"
Wert aus fixtures verwenden (spec/fixtures/termination_reasons.yml)

2024-07-09 20:36 UTC, rnestler commented on spec/features/memberships/leave_zusatzsektion_spec.rb
> +      select "einfach so"
Done.

2024-07-09 20:53 UTC, rnestler commented on app/views/wizards/steps/leave_zusatzsektion/_summary.html.haml
> +    = form.select :termination_reason, ['einfach so', 'weiss nicht'], {prompt: true}
Musste es ein wenig anders machen, da sonst die id_s nicht richtig gemappt wurden.

2024-07-09 20:54 UTC, merged