EVENTS: Zusätzliche Felder Kurs
hitobito/hitobito_sac_cas pull request #700
Opened 2024-07-03 12:51 UTC by hunchr

Fixes #669

2024-07-03 14:53 UTC, hunchr commented on spec/models/event/course_spec.rb
> -  describe '#maximum_age' do
diese specs wurden gelöscht, weil jetzt nicht mehr über `event_kinds` delegated wird`

2024-07-08 12:06 UTC, mtnstar requested changes
yay, das xeht scho sehr guet us :partying_face: 

neben den ganz kleinen Inputs, würde es Sinn machen einen Test zu schreiben für das 'Werte übernehmen' + 'Daten auf Kurse übertragen'
sicherstellen das dort die Werte entsprechend applied werden?

2024-07-08 12:06 UTC, mtnstar commented on app/models/sac_cas/event/course.rb
> +#  maximum_age                      :integer
diese werte sind ja auf der db ... idealerweise müsstest du diese auch in SacCas::Event ergänzen.
oft wird die info auch noch in den fixture files hinterlegt.
aber ich mag das eigentlich auch nicht so und es wurde beim SAC wagon kaum gemacht

2024-07-08 12:20 UTC, hunchr commented on spec/models/event/kind_spec.rb
> +        maximum_class_size: 2,
neben den ganz kleinen Inputs, würde es Sinn machen einen Test zu schreiben für das 'Werte übernehmen' + 'Daten auf Kurse übertragen'
sicherstellen das dort die Werte entsprechend applied werden?

2024-07-16 09:56 UTC, mtnstar approved these changes
nice, merge it :partying_face:

2024-07-16 10:01 UTC, merged