PEOPLE: Datenqualität in TableDisplay
hitobito/hitobito_sac_cas pull request #834
Opened 2024-08-14 12:32 UTC by hunchr

Fixes #792

2024-08-19 07:41 UTC, hunchr commented on app/domain/table_displays/resolving_column.rb
>      end
es wird zwar sortiert, aber nicht richtig

2024-08-21 13:07 UTC, njaeggi requested changes
LGTM, just some small suggestions

2024-08-21 13:07 UTC, njaeggi commented on spec/features/people/list_spec.rb
> +  end
I would suggest adding a spec for all different icons possible and then checking

`expect(find("td[data-attribute-name="data_quality"] i")).to have_css('fas fa-check-circle')`
or
`expect(find("td[data-attribute-name="data_quality"] i")).to have_css('fas fa-check-info')`

2024-08-21 14:00 UTC, njaeggi approved these changes
:rocket:

2024-08-21 14:19 UTC, merged