Feature/sac 843 transmit members abacus
hitobito/hitobito_sac_cas pull request #890
Opened 2024-08-29 14:13 UTC by Largo

Bitte um Feedback

2024-08-30 08:47 UTC, codez requested changes
Noch einige Specs, ansonsten schaut es gut aus.

2024-08-30 08:47 UTC, codez commented on app/domain/invoices/abacus/subject.rb
> +      ].freeze
Hier sollten nur die "Datenattribute" drin sein, `id` und `abacus_subject_key` also nicht. Diese beiden müssen dann bei Bedarf zusätzlich angegeben werden (siehe unten).

2024-08-30 08:47 UTC, codez commented on app/jobs/invoices/abacus/transmit_all_members_job.rb
> +    people = Person.where(id: slice).select(*RELEVANT_ATTRIBUTES)
Hier oder in der Konstante in dieser Klasse müssten dann id und abacus_subject_key zusätzlich mitgegeben werden.

2024-08-30 08:47 UTC, codez commented on spec/jobs/invoices/abacus/transmit_all_members_job_spec.rb
> +  end
Diese Specs mocken mir noch zuviel weg, das Zusammenspiel der einzelnen Methoden wird damit nicht getestet. Ich fände mindestens einen Blackbox Test elementar, welcher nur `SubjectInterface#transmit_batch` mockt, und dabei auch die erwarteten Subjects prüft und unterschiedliche Parts (z.B. einzelne mit Fehlern) zurück gibt.

Dabei wäre es wohl sinnvoll, gleich mit allen People Fixtures zu arbeiten und diese nicht mit Person.destroy_all zu löschen.

2024-08-30 08:47 UTC, codez commented on spec/jobs/invoices/abacus/transmit_all_members_job_spec.rb
> +  end
Hier fehlt mir auch noch Tests, welche die parallele Verarbeitung inkl. Batches, Slices und Exception Handling überprüfen. Werden z.B. andere Threads sauber beendet, wenn einer eine Exception wirft?

2024-09-04 07:02 UTC, codez requested changes

2024-09-04 07:02 UTC, codez commented on spec/jobs/invoices/abacus/transmit_all_members_job_spec.rb
> +      allow(Parallel).to receive(:map) do |slices, options, &block|
Hier dasselbe. Momentan ist der Code im Test sehr ähnlich wie der Code im Job, dadurch können wir schliessen, dass der Job korrekt arbeitet. Aber wenn der Code im Job ändert und einen Fehler hervorbringt, wird das mit diesem Test nicht entdeckt. Darum würde ich unbedingt das Thread-Handling vom Job testen und nicht dessen Abbild.

2024-09-04 07:56 UTC, Largo commented on spec/jobs/invoices/abacus/transmit_all_members_job_spec.rb
> +      allow(Parallel).to receive(:map) do |slices, options, &block|
Parallel selber musste ich nachbauen, aber der Code innerhalb wird genau gleich ausgeführt.

2024-09-04 12:05 UTC, merged