Feature/801/create invoice for neuanmeldungen
hitobito/hitobito_sac_cas pull request #891
Opened 2024-08-29 14:57 UTC by njaeggi

2024-08-30 11:53 UTC, TheWalkingLeek requested changes
Was zusätzlich glaub noch komplett fehlt sind die changes an `CreateMembershipInvoiceJob`
Können am Montag gerne auch zusammen drauf schauen :)

2024-08-30 11:53 UTC, TheWalkingLeek commented on app/models/wizards/signup/sektion_operation.rb
> +    def invoice_date = @invoice_date ||= [Date.current, register_on.change(day: 15, month: register_on.month - 1)].max
Ich glaub wenn `register_on` im Januar wäre würds dann versuchen ein Datum im Monat 0 zu erstellen oder? x)

Mach doch einen zwei Zeiler draus
```
def invoice_date
@invoice_date ||= begin
  invoice_cutoff_date = (register_on - 1.month).change(day: 15) # vielleicht kann man das noch etwas leserlicher machen idk
  [Date.current, invoice_cutoff_date].max
end
end
```

2024-08-30 11:53 UTC, TheWalkingLeek commented on app/models/wizards/signup/sektion_operation.rb
> +      if can_receive_invoice?
Jetzt guarden sowohl `no_approval_needed?` als auch `can_receive_invoice?` diese Logik aber an verschiedenen Stellen. Gibts dazu einen Grund oder kann man das an die selbe Stelle setzen? (imo im `#save!`)

2024-08-30 11:53 UTC, TheWalkingLeek commented on spec/domain/people/neuanmeldungen/approve_spec.rb
> +  def create_role(beitragskategorie, person: nil)
```suggestion
  def create_role(beitragskategorie, person: Fabricate(:person, birthday: 20.years.ago, sac_family_main_person: true))
```
So müsste das Fabricate glaub der default wert sein dann kannst du unten das `||` lassen

2024-08-30 11:53 UTC, TheWalkingLeek commented on app/models/wizards/signup/sektion_operation.rb
> +    def no_approval_needed? = Group::SektionsNeuanmeldungenSektion.where(layer_group_id: role.group.layer_group_id).none?
Sollte das noch das `archived_at` betrachten oder ignorieren wir das? Und was ist bei soft deletion (`deleted_at`) ? @daniel-illi

2024-08-30 11:53 UTC, TheWalkingLeek commented on spec/models/wizards/signup/sektion_operation_spec.rb
> +    it "#save! creates invoice and starts job" do
Kannst du den Test vielleicht umschreiben sodass `register_on` nicht `today` ist? 
Weil eigentlich wäre ja die assumption dass issued_at & sent_at `= Date.current` und nicht `today` sind.
Zudem ist (zumindest was ich dem Ticket entnehme) `register_on` immer am ersten vom nächsten Monat (oder?) Daher etwas verwirrend dass das hier im Test grundsätzlich `today` sein kann
Am besten auch noch in einen context block damits gleich strukturiert ist wie auf Zeile 106

2024-09-02 12:46 UTC, njaeggi commented on app/models/wizards/signup/sektion_operation.rb
> +    def invoice_date = @invoice_date ||= [Date.current, register_on.change(day: 15, month: register_on.month - 1)].max
Date.new(2000, 01, 01) - 1.month
=> Wed, 01 Dec 1999

`- 1.month` rechnet mit effektiven Date Ranges, auch Schaltjahre (29. Februar werden richtig beachtet)

2024-09-03 07:07 UTC, njaeggi commented on app/models/wizards/signup/sektion_operation.rb
> +    def no_approval_needed? = Group::SektionsNeuanmeldungenSektion.where(layer_group_id: role.group.layer_group_id).none?
Ich denke das sobald die Neuanmeldungs Gruppe archiviert oder gelöscht "soft deleted" wurde, wird für die Neuanmeldung kein Approval mehr nötig sein

Auf Benutzerebene existiert diese Gruppe zu dem Zeitpunkt nicht mehr

2024-09-03 12:58 UTC, TheWalkingLeek approved these changes
LGTM, bitte nochmal durchklicken dann mergen :)

2024-09-04 06:11 UTC, merged