Add mail template for membership activation
hitobito/hitobito_sac_cas pull request #952
Opened 2024-09-12 11:24 UTC by hunchr

Fixes #930

2024-09-13 07:13 UTC, amaierhofer requested changes

2024-09-13 09:31 UTC, hunchr commented on db/seeds/custom_contents.rb
> +  {key: Invoices::SacMembershipsMailer::MEMBERSHIP_ACTIVATED,
ok, aber wie kann ich den path dann dort einsetzen? etwas wie
`{body: "... im <a href='{{group_person_url(@person.default_group_id, @person.id)}}'>SAC-Portal</a> ..."}` geht ja nicht

2024-09-17 13:24 UTC, amaierhofer commented on db/seeds/custom_contents.rb
> +  {key: Invoices::SacMembershipsMailer::MEMBERSHIP_ACTIVATED,
ja, du hast recht, es braucht den placeholder, stimmt so

2024-09-17 13:24 UTC, amaierhofer commented on app/mailers/invoices/sac_memberships_mailer.rb
> +class Invoices::SacMembershipsMailer < ApplicationMailer
Hier fehlt noch die mailer spec

2024-09-18 12:47 UTC, amaierhofer approved these changes

2024-09-18 12:54 UTC, merged