Update family members step UI
hitobito/hitobito_sac_cas pull request #991
Opened 2024-09-19 07:20 UTC by hunchr

Fixes #985

2024-09-19 07:21 UTC, hunchr commented on config/locales/wagon.de.yml
> +      add: Weiteres Familienmitglied hinzufügen
brauchen wir das sonst noch wo? das ist ja im globals, aber wird bis jetzt nur für family members verwendet

2024-09-23 09:07 UTC, hunchr commented
ich bin mir nicht sicher, weshalb die specs failen. könnte eine race condition sein?

2024-09-24 10:37 UTC, TheWalkingLeek requested changes
Ich glaube da brauchen wir noch eine andere Lösung als einfach den translation value anzupassen...

Im core wird das unter `StandardFormBuilder#nested_fields_for` eingefügt.. Vielleicht musst du das `options` Argument verwenden um den Text beim Call weiterzugeben. Braucht natürlich auch einen PR im Core aber ist denke ich der schlauste Weg

2024-09-24 10:37 UTC, TheWalkingLeek commented on config/locales/wagon.de.yml
> +      add: Weiteres Familienmitglied hinzufügen
Ja schon allein auf dem `people#edit` aber auch `events#new/edit` das können wir nicht hier im globals überschreiben

2024-09-24 13:23 UTC, hunchr commented on config/locales/wagon.de.yml
> +      add: Weiteres Familienmitglied hinzufügen
oh fail, stimmt

2024-09-24 13:23 UTC, hunchr commented on config/locales/wagon.de.yml
> +      add: Weiteres Familienmitglied hinzufügen
oh stimmt

2024-09-26 09:02 UTC, TheWalkingLeek approved these changes

2024-09-26 10:09 UTC, hunchr commented
@TheWalkingLeek die specs failen immer noch, die sind denke ich nicht flaky, es liegt an etwas anderem. weisst du an was? ref https://github.com/hitobito/hitobito_sac_cas/pull/991#issuecomment-2367629002

2024-09-26 13:08 UTC, merged