Use stimulus controller for dependent checkboxes and add specs
hitobito/hitobito_sac_cas pull request #994
Opened 2024-09-19 11:42 UTC by njaeggi

2024-09-23 06:57 UTC, TheWalkingLeek requested changes
Mir sind beim Durchtesten noch zwei Dinge aufgefallen:
1. Ich kann als normaler Nutzer soweit ich sehe nie auf den `TerminateSacMembershipWizard` navigieren. Im Dropdown wird ein can? für die Wizard Konstante aufgerufen aber der Wizard hat keine Ability => gibt immer `false` https://github.com/hitobito/hitobito_sac_cas/blob/master/app/helpers/dropdown/people/memberships.rb#L37
2. Ich kann das "Daten aufbewahren" Checkmark einfach händisch wieder abwählen. So kann ein Zustand entstehen, bei dem der "Daten aufbewahern" unchecked und zB "Spenden" checked. Soll das so? Wenn nicht müsste man das wohl im UI locken und es bräuchte eine Backend Validierung

2024-09-23 06:57 UTC, TheWalkingLeek commented on spec/features/memberships/sac_terminate_membership_wizard_spec.rb
> +    it "check newsletter and sac spenden uncheck one, doesnt uncheck data_retention_consent" do
```suggestion
    it "do not uncheck data_retention_consent when unchecking newsletter or sac spenden" do
```

2024-09-23 06:57 UTC, TheWalkingLeek commented on spec/features/memberships/sac_terminate_membership_wizard_spec.rb
> +      expect(find("#wizards_memberships_terminate_sac_membership_wizard_summary_data_retention_consent")).to be_checked
```suggestion
      expect(find("#wizards_memberships_terminate_sac_membership_wizard_summary_data_retention_consent")).to be_checked
            
uncheck "Ich möchte weiterhin über Spendenaktionen informiert werden."
expect(find("#wizards_memberships_terminate_sac_membership_wizard_summary_data_retention_consent")).to be_checked
```

Noch testen obs beim anderen Feld auch so ist

2024-10-11 10:47 UTC, amaierhofer requested changes
Bitte noch auf stimulus targets umstellen. Zudem soll noch geprüft werden, warum dem select diese css klassen fehlen. Das sollte imho schon vom core kommen, sonst haben wir da immer wieder Inkonsistenzen.

2024-10-11 10:47 UTC, amaierhofer commented on app/views/wizards/steps/leave_zusatzsektion/_summary.html.haml
> +    = form.select :termination_reason_id, c.model.termination_reason_options, {prompt: true}, class: "form-select form-select-sm"
sollte das nicht schon via `StandardFormBuilder` mitkommen?

2024-10-11 10:47 UTC, amaierhofer commented on app/views/wizards/steps/termination/_summary.html.haml
> +      = form.select :termination_reason_id, c.model.termination_reason_options, {prompt: true}, class: "form-select form-select-sm"
sollte das nicht schon via `StandardFormBuilder` mitkommen?

2024-10-14 11:19 UTC, njaeggi commented on app/views/wizards/steps/termination/_summary.html.haml
> +      = form.select :termination_reason_id, c.model.termination_reason_options, {prompt: true}, class: "form-select form-select-sm"
Grundsätzlich ja... die select helper methode wird nur nicht überschrieben im `StandardFormBuilder`, während dem Bootstrap Upgrade wurde darüber geredet diese zu überschreiben und die beiden Klassen direkt zu geben. Da schon auf vielen selects (mittlerweile eigentlich alle) von Hand Klassen gesetzt werden, wurde entschieden dies nicht zu tun, da wir entweder überall diese Klassen entfernen müssten oder überall die Klassen danach doppelt haben (`class="form-select form-select-sm form-select form-select-sm"`) 

Meiner Meinung nach würde es jedoch durchaus Sinn machen dies im `StandardFormBuilder` zu setzen

2024-10-14 11:35 UTC, njaeggi commented
CI Run mit Core Branch: https://github.com/hitobito/hitobito_sac_cas/actions/runs/11326699506

2024-10-23 14:52 UTC, merged